name: Publish

on:
  push:
    branches:
      - 'main'

env:
  NODE_VERSION: 20
  PNPM_VERSION: 9

jobs:
  publish-js:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: true

      - name: Publish frontend-utils
        uses: ./.github/actions/publish-one
        with:
          package: frontend-utils
          secret-npm-token: ${{ secrets.NPM_TOKEN }}
